language: python
python:
- 3.7
- 3.8
cache:
  pip: true
  apt: true
  directories:
  - "$HOME/.pip-cache"
install:
- pip install pytest
- pip install .
script:
- pytest
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  provider: pypi
  username: "__token__"
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true
  password: $PYPI_TOKEN